package bean;
// Generated 14/08/2024 11:12:40 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OibCliente generated by hbm2java
 */
@Entity
@Table(name = "oib_cliente",
        catalog = "db_oscar_iago"
)
public class OibCliente implements java.io.Serializable {

    private int idOibCliente;
    private String oibNome;
    private String oibSobrenome;
    private String oibCpf;
    private Date oibDatanascimento;
    private String oibGenero;
    private String oibEmail;
    private String oibTelefone;
    private String oibEstado;
    private String oibSenha;
    private String oibRg;
    private String oibEndereco;
    private String oibTipo;
    private String oibEstadocivil;
    private String oibCep;

    public OibCliente() {
    }

    public OibCliente(int idOibCliente) {
        this.idOibCliente = idOibCliente;

    }

    public OibCliente(int idOibCliente, String oibNome, String oibSobrenome, String oibCpf, Date oibDatanascimento, String oibGenero, String oibEmail, String oibTelefone, String oibEstado, String oibSenha, String oibRg, String oibEndereco, String oibTipo, String oibEstadocivil, String oibCep) {
        this.idOibCliente = idOibCliente;
        this.oibNome = oibNome;
        this.oibSobrenome = oibSobrenome;
        this.oibCpf = oibCpf;
        this.oibDatanascimento = oibDatanascimento;
        this.oibGenero = oibGenero;
        this.oibEmail = oibEmail;
        this.oibTelefone = oibTelefone;
        this.oibEstado = oibEstado;
        this.oibSenha = oibSenha;
        this.oibRg = oibRg;
        this.oibEndereco = oibEndereco;
        this.oibTipo = oibTipo;
        this.oibEstadocivil = oibEstadocivil;
        this.oibCep = oibCep;
    }

    @Id

    @Column(name = "id_oib_cliente", unique = true, nullable = false)
    public int getIdOibCliente() {
        return this.idOibCliente;
    }

    public void setIdOibCliente(int idOibCliente) {
        this.idOibCliente = idOibCliente;
    }

    @Column(name = "oib_nome", nullable = false, length = 20)
    public String getOibNome() {
        return this.oibNome;
    }

    public void setOibNome(String oibNome) {
        this.oibNome = oibNome;
    }

    @Column(name = "oib_sobrenome", nullable = false, length = 25)
    public String getOibSobrenome() {
        return this.oibSobrenome;
    }

    public void setOibSobrenome(String oibSobrenome) {
        this.oibSobrenome = oibSobrenome;
    }

    @Column(name = "oib_cpf", nullable = false, length = 14)
    public String getOibCpf() {
        return this.oibCpf;
    }

    public void setOibCpf(String oibCpf) {
        this.oibCpf = oibCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "oib_datanascimento", nullable = false, length = 10)
    public Date getOibDatanascimento() {
        return this.oibDatanascimento;
    }

    public void setOibDatanascimento(Date oibDatanascimento) {
        this.oibDatanascimento = oibDatanascimento;
    }

    @Column(name = "oib_genero", nullable = false, length = 10)
    public String getOibGenero() {
        return this.oibGenero;
    }

    public void setOibGenero(String oibGenero) {
        this.oibGenero = oibGenero;
    }

    @Column(name = "oib_email", nullable = false, length = 40)
    public String getOibEmail() {
        return this.oibEmail;
    }

    public void setOibEmail(String oibEmail) {
        this.oibEmail = oibEmail;
    }

    @Column(name = "oib_telefone", nullable = false, length = 15)
    public String getOibTelefone() {
        return this.oibTelefone;
    }

    public void setOibTelefone(String oibTelefone) {
        this.oibTelefone = oibTelefone;
    }

    @Column(name = "oib_estado", nullable = false, length = 2)
    public String getOibEstado() {
        return this.oibEstado;
    }

    public void setOibEstado(String oibEstado) {
        this.oibEstado = oibEstado;
    }

    @Column(name = "oib_senha", nullable = false, length = 30)
    public String getOibSenha() {
        return this.oibSenha;
    }

    public void setOibSenha(String oibSenha) {
        this.oibSenha = oibSenha;
    }

    @Column(name = "oib_rg", nullable = false, length = 10)
    public String getOibRg() {
        return this.oibRg;
    }

    public void setOibRg(String oibRg) {
        this.oibRg = oibRg;
    }

    @Column(name = "oib_endereco", nullable = false, length = 40)
    public String getOibEndereco() {
        return this.oibEndereco;
    }

    public void setOibEndereco(String oibEndereco) {
        this.oibEndereco = oibEndereco;
    }

    @Column(name = "oib_tipo", nullable = false, length = 15)
    public String getOibTipo() {
        return this.oibTipo;
    }

    public void setOibTipo(String oibTipo) {
        this.oibTipo = oibTipo;
    }

    @Column(name = "oib_estadocivil", nullable = false, length = 20)
    public String getOibEstadocivil() {
        return this.oibEstadocivil;
    }

    public void setOibEstadocivil(String oibEstadocivil) {
        this.oibEstadocivil = oibEstadocivil;
    }

    @Column(name = "oib_cep", nullable = false, length = 10)
    public String getOibCep() {
        return this.oibCep;
    }

    public void setOibCep(String oibCep) {
        this.oibCep = oibCep;
    }

    @Override
    public String toString() {
        return this.oibNome;
    }

    @Override
    public boolean equals(Object object) {
        if (object instanceof OibCliente) {
            OibCliente oibCliente = (OibCliente) object;
            if (this.getIdOibCliente() == oibCliente.getIdOibCliente()) {
                return true;
            }
        }
        return false;
    }

}
