package bean;
// Generated 14/08/2024 11:12:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OibProduto generated by hbm2java
 */
@Entity
@Table(name="oib_produto"
    ,catalog="db_oscar_iago"
)
public class OibProduto  implements java.io.Serializable {


     private int idOibProduto;
     private String oibNome;
     private String oibCor;
     private String oibEspecie;
     private double oibPreco;
     private int oibQuantidade;
     private String oibTamanho;

    public OibProduto() {
    }

	
    public OibProduto(int idOibProduto) {
        this.idOibProduto = idOibProduto;

    }
    public OibProduto(int idOibProduto, String oibNome, String oibCor, String oibEspecie, double oibPreco, int oibQuantidade, String oibTamanho) {
       this.idOibProduto = idOibProduto;
       this.oibNome = oibNome;
       this.oibCor = oibCor;
       this.oibEspecie = oibEspecie;
       this.oibPreco = oibPreco;
       this.oibQuantidade = oibQuantidade;
       this.oibTamanho = oibTamanho;
    }
   
     @Id 

    
    @Column(name="id_oib_produto", unique=true, nullable=false)
    public int getIdOibProduto() {
        return this.idOibProduto;
    }
    
    public void setIdOibProduto(int idOibProduto) {
        this.idOibProduto = idOibProduto;
    }

    
    @Column(name="oib_nome", nullable=true, length=30)
    public String getOibNome() {
        return this.oibNome;
    }
    
    public void setOibNome(String oibNome) {
        this.oibNome = oibNome;
    }

    
    @Column(name="oib_cor", nullable=true, length=20)
    public String getOibCor() {
        return this.oibCor;
    }
    
    public void setOibCor(String oibCor) {
        this.oibCor = oibCor;
    }

    
    @Column(name="oib_especie", nullable=true, length=20)
    public String getOibEspecie() {
        return this.oibEspecie;
    }
    
    public void setOibEspecie(String oibEspecie) {
        this.oibEspecie = oibEspecie;
    }

    
    @Column(name="oib_preco", nullable=true, precision=10)
    public double getOibPreco() {
        return this.oibPreco;
    }
    
    public void setOibPreco(double oibPreco) {
        this.oibPreco = oibPreco;
    }

    
    @Column(name="oib_quantidade", nullable=true)
    public int getOibQuantidade() {
        return this.oibQuantidade;
    }
    
    public void setOibQuantidade(int oibQuantidade) {
        this.oibQuantidade = oibQuantidade;
    }

    
    @Column(name="oib_tamanho", nullable=true, length=1)
    public String getOibTamanho() {
        return this.oibTamanho;
    }
    
    public void setOibTamanho(String oibTamanho) {
        this.oibTamanho = oibTamanho;
    }





}


