package bean;
// Generated 14/08/2024 11:12:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OibVenda generated by hbm2java
 */
@Entity
@Table(name="oib_venda"
    ,catalog="db_oscar_iago"
)
public class OibVenda  implements java.io.Serializable {


     private int idOibVenda;
     private OibCliente oibCliente;
     private OibFuncionario oibFuncionario;
     private Date oibData;
     private String oibTotal;
     private String oibFormapagamento;

    public OibVenda() {
    }

	
    public OibVenda(int idOibVenda) {
        this.idOibVenda = idOibVenda;

    }
    public OibVenda(int idOibVenda, OibCliente oibCliente, OibFuncionario oibFuncionario, Date oibData, String oibTotal, String oibFormapagamento) {
       this.idOibVenda = idOibVenda;
       this.oibCliente = oibCliente;
       this.oibFuncionario = oibFuncionario;
       this.oibData = oibData;
       this.oibTotal = oibTotal;
       this.oibFormapagamento = oibFormapagamento;
    }
   
     @Id 

    
    @Column(name="id_oib_venda", unique=true, nullable=false)
    public int getIdOibVenda() {
        return this.idOibVenda;
    }
    
    public void setIdOibVenda(int idOibVenda) {
        this.idOibVenda = idOibVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="oib_fkcliente", nullable=false)
    public OibCliente getOibCliente() {
        return this.oibCliente;
    }
    
    public void setOibCliente(OibCliente oibCliente) {
        this.oibCliente = oibCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="oib_fkfuncionario", nullable=false)
    public OibFuncionario getOibFuncionario() {
        return this.oibFuncionario;
    }
    
    public void setOibFuncionario(OibFuncionario oibFuncionario) {
        this.oibFuncionario = oibFuncionario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="oib_data", nullable=false, length=10)
    public Date getOibData() {
        return this.oibData;
    }
    
    public void setOibData(Date oibData) {
        this.oibData = oibData;
    }

    
    @Column(name="oib_total", nullable=false, length=30)
    public String getOibTotal() {
        return this.oibTotal;
    }
    
    public void setOibTotal(String oibTotal) {
        this.oibTotal = oibTotal;
    }

    
    @Column(name="oib_formapagamento", nullable=false, length=15)
    public String getOibFormapagamento() {
        return this.oibFormapagamento;
    }
    
    public void setOibFormapagamento(String oibFormapagamento) {
        this.oibFormapagamento = oibFormapagamento;
    }




}


