package bean;
// Generated 14/08/2024 11:12:40 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OibVendaproduto generated by hbm2java
 */
@Entity
@Table(name = "oib_vendaproduto",
         catalog = "db_oscar_iago"
)
public class OibVendaproduto implements java.io.Serializable {

    private int idOibVendaproduto;
    private OibProduto oibProduto;
    private OibVenda oibVenda;
    private int oibQuantidade;
    private double oibValorunitario;

    public OibVendaproduto() {
    }

    public OibVendaproduto(int idOibVendaproduto, OibProduto oibProduto, OibVenda oibVenda, int oibQuantidade, double oibValorunitario) {
        this.idOibVendaproduto = idOibVendaproduto;
        this.oibProduto = oibProduto;
        this.oibVenda = oibVenda;
        this.oibQuantidade = oibQuantidade;
        this.oibValorunitario = oibValorunitario;
    }

    @Id

    @Column(name = "id_oib_vendaproduto", unique = true, nullable = false)
    public int getIdOibVendaproduto() {
        return this.idOibVendaproduto;
    }

    public void setIdOibVendaproduto(int idOibVendaproduto) {
        this.idOibVendaproduto = idOibVendaproduto;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "oib_fkproduto", nullable = false)
    public OibProduto getOibProduto() {
        return this.oibProduto;
    }

    public void setOibProduto(OibProduto oibProduto) {
        this.oibProduto = oibProduto;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "oib_fkvenda", nullable = false)
    public OibVenda getOibVenda() {
        return this.oibVenda;
    }

    public void setOibVenda(OibVenda oibVenda) {
        this.oibVenda = oibVenda;
    }

    @Column(name = "oib_quantidade", nullable = false)
    public int getOibQuantidade() {
        return this.oibQuantidade;
    }

    public void setOibQuantidade(int oibQuantidade) {
        this.oibQuantidade = oibQuantidade;
    }

    @Column(name = "oib_valorunitario", nullable = false, precision = 10)
    public double getOibValorunitario() {
        return this.oibValorunitario;
    }

    public void setOibValorunitario(double oibValorunitario) {
        this.oibValorunitario = oibValorunitario;
    }



}
